### PR TITLE
net-print/brother-mfc-j985dw-bin: new package, version 1.0.0

### PR DESCRIPTION
**Pull request by sbraz**
I had to disable `FEATURES=sign`, I hope that's fine. It's my first time committing for an overlay and not a fork of the main tree.
The filter is a script that more or less self generates, I didn't feel like doing that in the ebuild so I included the generated script in `${FILESDIR}`, I assume I'm allowed to do that since it includes its licence.

I didn't add myself as a maintainer because I'm not sure I'm competent to actually _maintain_ this. All I know is that I tried to keep it as clean as possible and that it works for me.

Inspired by https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brother-mfc-j985dw
and https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brother-mfc-j5720dw

Thanks to @AngryUbuntuNerd and @severach, I hope you guys are OK with me using your stuff from your PKGBUILDs.

### CODE REVIEW

**Comment by stefan-langenmaier** [comment]
Hi @sbraz,

thanks for the pull request. I think the approach with the filter script is okay. This way it's easier to reproduce problems in case of an error.

There are no strict rules on maintainership. Everything is provided on a best effort basis and the more people we have to look over the ebuilds the better! If you don't add yourself to the maintainer list you might get contacted less. :)

**Comment by sbraz** [comment]
Thanks for the merge :) Obviously if the driver has an issue and someone reports it, feel free to mention me!
I was surprised that there were no drivers as this printer seemed popular (rather cost-efficient inkjet which got good reviews). Let's hope my ebuild will be useful for other users!

**Comment by stefan-langenmaier** [comment]
Great, I'll keep you in mind!

**Comment by severach** [comment]
It's fine. IIRC all PKGBUILD released on the AUR are automatically released under a license which I can't find right now. That license specifically permits packagers in Arch or any other distro to use and adapt the code as desired.

**Pull request merged**
